version: "3.9"

services:
  pacer-svc:
    image: pacer-svc-img
    hostname: pacer-svc
    container_name: pacer-svc
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
    volumes:
      - pacer_volume:/app

volumes:
  pacer_volume: